### ISSUE TITLE
occur DatabaseException

### ISSUE THREAD

**Issue by wihy** [synw/kvsql#1]
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: DatabaseException(open_failed /Users/xxxx/Library/Developer/CoreSimulator/Devices/4BA6AD1A-A1EC-46FA-BF77-2C7B725E6A8F/data/Containers/Data/Application/572DEAF1-3314-4E8A-843A-8AF30FF645CF/Documents/icert_a.db)

**Comment by wihy** [comment]
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: DatabaseException(open_failed /Users/xxxx/Library/Developer/CoreSimulator/Devices/4BA6AD1A-A1EC-46FA-BF77-2C7B725E6A8F/data/Containers/Data/Application/572DEAF1-3314-4E8A-843A-8AF30FF645CF/Documents/icert_a.db)
#0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:12:7)
<asynchronous suspension>
#1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:25:7)
#2      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite/src/database_mixin.dart:188:15)
#3      SqfliteDatabaseMixin.openDatabase (package:sqflite/src/database_mixin.dart:524:15)
#4      SqfliteDatabaseMixin.doOpen (package:sqflite/src/database_mixin.dart:617:28)
#5      SqfliteDatabaseOpenHelper.openDatabase (package:sqflite/src/database.dart:46:22)
#6      SqfliteDatabaseFactoryMixin.openDatabase.<anonymous closure> (package:sqflite/src/factory_mixin.dart:103:43)
<asynchronous suspension>
#7      ReentrantLock.synchronized.<<…>
